spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/instagram
    username: root
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/aws/instagram/back/instagram/upload

jwt:
  secret: IgwBE5D+D+639nDdSwWj/Dvil3XPM2r0UXemY0+jPklLsjfA2PRZf7SvG47lQOAWSndSz4BwxfP7kXwb/0RRmQ==